//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Service.java
//  @ Date : 2015-11-17
//  @ Author : 
//
//
package model.service;

public interface Service {
	public void execute(ServiceRequest request);
}
