//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ServiceRequest.java
//  @ Date : 2015-11-17
//  @ Author : 
//
//
package service;



public interface ServiceRequest {
	enum RequestState{
		isSuccess
	};
	public <T>T getObject(String key);
	public void addObject(String key, Object value);
	public <T>T removeObject(String key);
}
