//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : RequestImpl.java
//  @ Date : 2015-11-17
//  @ Author : 
//
//
package service;

import java.util.HashMap;
import java.util.Map;

public class ServiceRequestImpl implements ServiceRequest {
	private Map<String, Object> requests;
	public ServiceRequestImpl() {
		requests = new HashMap<String, Object>();
	}
	
	@Override
	public void addObject(String key, Object value) {
		requests.put(key, value);
	}
	
	@SuppressWarnings("unchecked")
	@Override
	public <T> T getObject(String key) {
		return (T) requests.get(key);
	}
	
	@SuppressWarnings("unchecked")
	@Override
	public <T> T removeObject(String key) {
		return (T) requests.remove(key);
	}
}
